global_costmap:
  global_frame: rb1_base_map
  robot_base_frame: rb1_base_base_footprint
  update_frequency: 5.0
  static_map: true
  # robot radius +safety_delta 0.25 + 0.02
  # set to permit drawing a trajectory through the narrowest door
#  inflation_radius: 0.35
##  inflation_layer:
##    enabled:              true
##    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
##    inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.
#  
#  static_layer:
#    enabled:              true
#    map_topic:            "/map"
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

