#Independent settings for the planner's costmap
global_costmap:
    publish_voxel_map: true
    global_frame: robot_odom
    robot_base_frame: robot_base_footprint
    update_frequency: 5.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    width: 30.0
    height: 30.0
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
    inflation_radius: 0.26
