<?xml version="1.0"?>
<robot name="rb2" xmlns:xacro="http://wiki.ros.org/xacro"> 

  <xacro:macro name="rb2" params="prefix publish_bf hq">

  <!-- Robot mechanical and motor parameters -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_width" value="0.220" />

  <!-- BASE FOOTPRINT -->
  <xacro:if value="${publish_bf}">
    <link name="${prefix}base_footprint">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <box size="0.001 0.001 0.001" />
          </geometry>
      </visual>
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
       <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link" />
    </joint>    
  </xacro:if>

  <!-- BASE_LINK -->
  <link name="${prefix}base_link">
    <inertial>
      <mass value="25.0" />
      <origin xyz="0 0 0" />
      <inertia  ixx="0.007" ixy="0.0"  ixz="0.0"  iyy="0.007"  iyz="0.0"  izz="0.78" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <xacro:if value="${hq}">
       <geometry>
	     <mesh filename="package://rb2_description/meshes/bases/rb2_base.stl"/>
       </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
       <geometry>
       <mesh filename="package://rb2_description/meshes/bases/rb2.stl"/>
       </geometry>
       </xacro:unless>
       <material name="darkgrey">
         <color rgba="0.1 0.1 0.1 1"/>
       </material>
    </visual>  
    <collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://rb2_description/meshes/bases/rb2_base.dae"/>
       </geometry>
    </collision>
  </link>
 
  <!-- DOCKING CONTACTS -->
  <joint name="${prefix}docking_joint" type="fixed">
    <origin xyz="0.361 0.0 0.0" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="${prefix}docking_contact_link" />
  </joint>    

  <!-- DOCKING LINK -->
  <link name="${prefix}docking_contact_link" />

  <!-- PICKING CONTACTS -->
  <joint name="${prefix}picking_joint" type="fixed">
    <origin xyz="0.476 0.0 0.116" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="${prefix}picking_contact_link" />
  </joint>    

  <!-- PICKING LINK -->
  <link name="${prefix}picking_contact_link" />

  <!-- FRONT CONTACTS -->
  <joint name="${prefix}front_joint" type="fixed">
    <origin xyz="0.476 0.0 0.116" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_contact_link" />
  </joint>    

  <!-- FRONT LINK -->
  <link name="${prefix}front_contact_link" />

  <!-- REAR CONTACTS -->
  <joint name="${prefix}rear_joint" type="fixed">
    <origin xyz="-0.476 0.0 0.116" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="${prefix}rear_contact_link" />
  </joint>    

  <!-- REAR LINK -->
  <link name="${prefix}rear_contact_link" />

  </xacro:macro>
</robot>

