# This file is loaded when reflector locator is running.
# Used just to change QR sizes and publish them with the same name (default: robot_ar_locator_#)

# TODO: Using regular expressions might allow us to remove id_type field

# "id_type":
# - "single": Used to specify a single ID
# - "range": Used to specify a range of IDs
# - "list": Used to specify a list of IDs
# "id":
# - If id_type is "single", use a single int: 4
# - If id_type is "range", use two comma-separated ints: 1, 6
# - If id_type is "list", use as many comma-separated ints as desired: 2, 7, 25, 1
# Use either "type" or "exact_name". Don't set any of them if you just want to change marker size
#   - "type": marker will be published as prefix_type_id (robot_cart_4).
#           Prefix will be taken from AlvarCameraLocator
#           Frequently used types are 'cart' and 'docking_station'
#   - "exact_name": marker will be published exactly as specified here (e.g. init_localization_marker).
#           Normally used with a single id object
# "size": Default value is 0.115

markers:
# - id_type: single
#   id: 11
#   size: 0.08
#
- id_type: range
  id: 1, 10
  size: 0.115
