# This file is loaded when reflector locator is not running.
# Used to remap from robot_ar_marker_# to robot_cart_#, robot_docking_station_# or any other

# TODO: Using regular expressions might allow us to remove id_type field

# "id_type":
# - "single": Used to specify a single ID
# - "range": Used to specify a range of IDs
# - "list": Used to specify a list of IDs
# "id":
# - If id_type is "single", use a single int: 4
# - If id_type is "range", use two comma-separated ints: 1, 6
# - If id_type is "list", use as many comma-separated ints as desired: 2, 7, 25, 1
# Use either "type" or "exact_name". Don't set any of them if you just want to change marker size
#   - "type": marker will be published as prefix_type_id (robot_cart_4).
#           Prefix will be taken from AlvarCameraLocator
#           Frequently used types are 'cart' and 'docking_station'
#   - "exact_name": marker will be published exactly as specified here (e.g. init_localization_marker).
#           Normally used with a single id object
# "size": Default value is 0.115

markers:
- id_type: single
  id: 1
  type: docking_station
  size: 0.115

- id_type: range
  id: 2, 10
  type: cart
  size: 0.115
