joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rb2_left_wheel_joing
joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rb2_right_wheel_joint

robotnik_base_control:
  type: rb2_controller/RB2Controller
  joint:
    right_wheel_joint:
        name: rb2_right_wheel_joint
        max_speed: 27.27 # rad/s
    left_wheel_joint:
        name: rb2_left_wheel_joint
        max_speed: 27.27 # rad/s    
    elevator_joint:
        name: rb2_elevator_platform_joint
  linear_speed_limit: 1.5 # m/s
  linear_acceleration_limit: 1.5 # m/s^2
  angular_speed_limit: 3 # rad/s
  angular_acceleration_limit: 3 # rad/s^2
  hard_brake: false
  odom_frame: rb2_odom
  robot_base_frame: rb2_base_footprint
  odom_broadcast_tf: true
  odom_topic: 'robotnik_base_control/odom'
  wheel_base: 0.453  # 0.569
  track_width: 0.07 # 0.543
  wheel_diameter: 0.220
  cmd_watchdog_duration: 0.3
  imu_watchdog_duration: 0.1
  imu_topic: 'imu/data'
  odom_publish_frequency: 100
  cmd_vel        : 'robotnik_base_control/cmd_vel'
  kinematic_mode : 'skid'
  motion_odometry: true
  in_motion_timer: 2.0

  set_digital_output_service_hw: robotnik_base_hw/set_digital_output
  has_elevator: true
  elevator_position_up: 0.05 # linear height (m)
  elevator_position_down: 0.0
  elevator_digital_output_up: 5
  elevator_digital_output_down: 6 
  elevator_digital_input_up: 48
  elevator_digital_input_down: 47
  reverse_logic: false # Make sure what logic is your robot using

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0



